name: "CloudFormation Change Set"
description: "GitHub Action that creates, updates, deletes and applies CloudFormation change sets"
inputs:
  METHOD:
    description: "The action type"
    required: true
  STACK_NAME:
    description: "CloudFormation stack name"
    required: true
  AWS_ACCESS_KEY_ID:
    description: "AWS_ACCESS_KEY_ID"
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "AWS_SECRET_ACCESS_KEY"
    required: true
  AWS_REGION:
    description: "AWS_REGION"
    required: true
  TEMPLATE_FILE:
    description: "Path to CloudFormation template"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "upload-cloud"
  color: "green"
